services:
  # Monolithic Web Service (Backend + Frontend Static assets)
  - type: web
    name: spreetail-shared-expenses
    env: node
    buildCommand: npm run build
    startCommand: npm run migrate && npm start
    envVars:
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: PGCONNECTIONSTRING
        fromDatabase:
          name: spreetail-expenses-db
          property: connectionString

databases:
  - name: spreetail-expenses-db
    plan: free
